# Generated by Django 5.1.1 on 2024-10-09 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_subscription.videouser')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_subscription.video')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rate', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_subscription.videouser')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_subscription.video')),
            ],
            options={
                'unique_together': {('user', 'video')},
            },
        ),
    ]
